### PR TITLE
Test Refactoring

### PR DESCRIPTION
**Pull request by vermiculus**
This PR has been made to track Travis's reactions to the commits. It's not done quite yet:

- [X] Split tests into files by functionality
- [x] Use fixtures
- [x] Test dependencies

### CODE REVIEW

**Comment by Bruce-Connor** [comment]
:+1:

**Comment by vermiculus** [comment]
Except for test dependencies, I'm done with this branch. I have asked this on [Emacs.SE](http://emacs.stackexchange.com/q/5951/2264), but I don't expect it's possible – a wrapper macro may be necessary if we actually want this functionality.

**Comment by Bruce-Connor** [comment]
Ok, besides the two comments, I'm good with merging. If there's no built-in way of defining dependencies, I say we don't worry about it. If both the tests for `assoc-let` and `ensure-site` fail, we'll know to look at `ensure-site` first.

**Comment by vermiculus** [comment]
Alright, I've marked 'test dependencies' as 'done' since we aren't going to need them (at least for a long while). Assuming Travis passes, I'll go ahead and merge.

**Pull request merged**
