### PR TITLE
Tag buttons

### LINKED ISSUE #229: Hangle [tag:tag-name] links
Links such as [tag:tag-name] should be rendered as tag buttons described in #230 . So that should probably be done first.

### LINKED ISSUE #230: Make tags into buttons
They should be buttons which, when interacted with, do a tag search.

### PR DESCRIPTION
**Pull request by Bruce-Connor**
Tags everywhere are buttons now. In-body tags also render pretty.

Fix #230 and Fix #229

### CODE REVIEW

**Comment by Bruce-Connor** [comment]
I'm not sure what's going on here. Travis doesn't even display the entire backtrace: https://travis-ci.org/vermiculus/sx.el/jobs/47253937#L358

**Comment by Bruce-Connor** [comment]
Also, my tests don't reproduce this.

**Comment by Bruce-Connor** [comment]
Great. Tests are passing.

**Comment by vermiculus** [comment]
:+1:

**Pull request merged**
