### PR TITLE
Use `data` branch for bot data

### PR DESCRIPTION
**Pull request by vermiculus**

### CODE REVIEW

**Comment by vermiculus** [comment]
The `gh-pages` branch may well have better response times, but we might run into an issue with merging into it. It may be able to be done by some complex git stashing maneuver and pushing only the `data/` directory to the branch, but I'm not sure exactly how that'd work.

**Comment by Bruce-Connor** [comment]
Is there a way we can test the response time? 
What if we push the data to the gh-pages branch just this once, and check if `time wget` yields a difference?

**Comment by Bruce-Connor** [comment]
Ok, I did some very preliminary tests running `time (wget $URL &> /dev/null )`, with `URL` being `http://vermiculus.github.io/sx.el/auth/auth.htm` and `https://raw.githubusercontent.com/vermiculus/sx.el/data/data/stats.el` (because both were roughly the same size).
The `gh-pages` one averaged at about 0.45 seconds, and the `data` branch one averaged at amost twice that much (they were both very consistent).

Then I tried the `data` branch without `https`, and it averaged at 0.45 as well. So it seems there's no difference in response times as long as we just use `http`.

**Comment by Bruce-Connor** [comment]
Ok. I merged master into this, then changed our data url from https to http.
If you're good with the changes merge away.

**Pull request merged**
