### PR TITLE
Meta tags

### PR DESCRIPTION
**Pull request by Bruce-Connor**
`[tag:` links in a meta question refer to the main site.
`[meta-tag:` links refer to the meta site.

### CODE REVIEW

**Comment by Bruce-Connor** [comment]
I was surprised to find out `[tags:TAG]` is an acceptable format (notice the `s`). For reference: http://meta.emacs.stackexchange.com/a/262/50

**Comment by vermiculus** [comment]
I looked at the link you provided and it appears that `[tags:text-properties]` gets rendered as just that – are you seeing something different?

**Comment by Bruce-Connor** [comment]
Oh, you're absolutely right. =P I just saw it in SX and assumed we were doing something wrong.

**Comment by Bruce-Connor** [comment]
Ok. I'm feeling dangerous today so I rewrote history to undo that. ;-)

**Comment by vermiculus** [comment]
:+1:

**Pull request merged**
